import type { Metadata } from "next";
import localFont from "next/font/local"; // Import localFont function
import { Roboto } from "next/font/google";
import { Suspense } from "react";
import AuthProvider from "./auth/AuthProvider";
import NavBar from "./components/NavBar";
import "./globals.css";
import GoogleAnalyticsScripts from "./GoogleAnalyticsScripts";

const poppins = localFont({
  // Create font object
  src: "../public/fonts/poppins-regular-webfont.woff2",
  variable: "--font-poppins", // Create CSS variable
});

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <GoogleAnalyticsScripts />
      <body className={poppins.className}>
        <AuthProvider>
          <NavBar />
          <main>{children}</main>
        </AuthProvider>
      </body>
    </html>
  );
}
